import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>HangHero</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>HangHero</h1>
      </main>
    </>
  );
};

export default Home;
